[phases.setup]
nixPkgs = ['go', 'chromium']

[phases.build]
cmds = ['go build -o app ./cmd/gotenberg/main.go']

[start]
cmd = './app'

[env]
CHROMIUM_BIN_PATH = "/nix/store/$(ls -t /nix/store | grep chromium | head -n1)/bin/chromium"
